- defaults:
    link:
      relink: true
      create: true
- clean: ['~']
- link:
    ~/.config/nvim: config/neovim
    ~/.config/vimwiki: config/vimwiki
- create:
    - ~/.vim/undo-history
- shell:
  - [git submodule update --init --recursive, Installing submodules]
