name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Run Scoop
      run: runas /trustlevel:0x10000 "powershell.exe -command ./install.ps1"
      shell: pwsh
    - name: Run the installer
      run: ./install.sh
      shell: bash
